apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- project.yaml
- credentials/infrastructure-secrets.yaml
- credentials/secretbindings.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: provider-extensions.login
  namespace: garden
  files:
  - kubeconfig=credentials/seed-kubeconfig.yaml
